env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
  - 'plugin:@typescript-eslint/recommended'
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier # eslint-plugin-prettier の追加
rules:
  # 関数の複雑さを 10 以下にする
  complexity: ['error', 10]
  # React のプロパティの型チェックを省略する (TypeScript でチェックされるため)
  react/prop-types: off
  # インターフェースの先頭文字を "I" にする
  "@typescript-eslint/naming-convention": [
      "error",
      {
          "selector": "interface",
          "format": ["PascalCase"],
          "custom": {
              "regex": "^I[A-Z]",
              "match": true
          }
      }
  ]

  # prettier のチェックでErrorとするための設定。
  prettier/prettier:
    - error
